Update the gem, and make it work with ups
TerraCycle/spree_active_shipping pull request #1
Opened 2019-08-01 10:34 UTC by SkayHUN

2019-08-06 21:27 UTC, AHolcsik approved these changes

2019-08-26 08:55 UTC, bluta requested changes

2019-08-26 08:55 UTC, bluta commented on lib/spree/active_shipping/ups.rb
> +module Spree
plz add a comment with where this was coming(/ is duplicated ;) ) from

2019-08-30 09:44 UTC, adamFoldvari approved these changes

2019-08-30 09:49 UTC, erik-terracycle commented on lib/spree_active_shipping/engine.rb
> +      # ActiveShipping::Carriers::CanadaPost.send(:include, Spree::ActiveShipping::CanadaPostOverride)
@SkayHUN Why did you comment out this line?

2019-08-30 10:27 UTC, storhet requested changes

2019-08-30 10:27 UTC, storhet commented on Gemfile
> +gem 'active_shipping', github: 'Shopify/active_shipping'
there is no need to add this to the Gemfile

2019-09-02 08:15 UTC, SkayHUN commented on lib/spree_active_shipping/engine.rb
> +      # ActiveShipping::Carriers::CanadaPost.send(:include, Spree::ActiveShipping::CanadaPostOverride)
we use only UPS, so we don't need CanadaPost right now.

2019-09-02 10:04 UTC, storhet approved these changes

2019-09-02 11:53 UTC, VasiliyMaksymov approved these changes

2019-09-03 10:10 UTC, bluta approved these changes

2019-09-03 10:10 UTC, merged